# Generated by Django 4.1.1 on 2022-09-10 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Gender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("undefined", "미선택"),
                            ("male", "남성"),
                            ("female", "여성"),
                        ],
                        default="undefined",
                        max_length=20,
                        verbose_name="성별",
                    ),
                ),
            ],
            options={"db_table": "gender",},
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "대기중"),
                            ("accept", "수락"),
                            ("disaccept", "반려"),
                        ],
                        default="waiting",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
            ],
            options={"db_table": "status",},
        ),
        migrations.CreateModel(
            name="ApplicantModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16, verbose_name="성명")),
                ("birthday", models.CharField(max_length=11, verbose_name="생일")),
                ("email", models.CharField(max_length=120, verbose_name="이메일")),
                ("phone_number", models.CharField(max_length=13, verbose_name="연락처")),
                (
                    "apply_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="신청날짜"),
                ),
                (
                    "gender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="applicant.gender",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="applicant.status",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artist_names",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "applicant",},
        ),
    ]
