# Generated by Django 4.1.1 on 2022-09-11 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applicant", "0001_initial"),
        ("art", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="ArtModel", new_name="Art",),
    ]
